### ISSUE TITLE
Remove the `state` argument

### ISSUE THREAD

**Issue by bendrucker** [hanford/angular-vdom#3]
If data management is handled by Angular then it should be 100% handled. You should not need to pass in initial state and instead should be defining an initial scope value to work off of.

**Comment by hanford** [comment]
@bendrucker Doesn't main-loop require an initState?

**Comment by bendrucker** [comment]
Sure but that needs to be supplied by Angular

**Comment by hanford** [comment]
Not entirely sure I understand what you mean by "needs to be supplied by angular" .. this sort of touches on #5 too.

What do you think the ideal way to pass in your model to the vdom components would look like? In the example I have a simple  ["count='count'"](https://github.com/hanford/angular-vdom/blob/master/example/index.html) binding where count is simply a $scope variable. 

Ideally we could just remove the `state` arguement and just move forward with `options.bindings`, but that would make this a lot more complex as we don't know the type of the binding, only the way it's binded: '<', '=', '@', etc .. ... This is like 50% of what I need, and this breaks on the initial render before the actual bindings are defined. 

The most sensible way I think I could move forward is under the assumption of a `$scope.state` object. Where you would basically need to define the schema of the model - that way when the $onChange function is called with `changes`, I'll know where to set that data. And the component could render before anything is defined which solves the `options.bindings` problem

**Comment by bendrucker** [comment]
> The most sensible way I think I could move forward is under the assumption of a $scope.state

Nope, bad idea. You need to be able to read the data from the Angular scope and/or not compile until you have it. You need to go read Angular source code and understand how to do it properly. Cheating is not allowed.

**Comment by bendrucker** [comment]
If it feels gross it is. If your goal here is that Angular manages data and v-dom renders that's a good goal. You need to execute on that. If you start mixing in coupling then it's not accomplishing that goal and I'd rather can the idea entirely.

**Comment by hanford** [comment]
[hmmm](https://github.com/hanford/angular-vdom/blob/0812cd9a518766e462eceffa010a235050576571/index.js#L15)

@bendrucker ^ seems like a mediocre solution and doesn't really work with Controller As, any better ideas?

I'm ok with $scope being a requirement for these values as you can have both controller As and $scope - however I feel like I'm missing a better solution. I could also loop over the $scope.$parent object and try to determine the controller As variable, hmmm

**Comment by bendrucker** [comment]
That doesn't really work either because then you just close over another value unnecessarily and have more cleanup and sync to do.

**Comment by hanford** [comment]
@bendrucker can you define 

>  just close over another value unnecessarily and have more cleanup and sync to do >

The above solution would work if the value is either a `$scope.value` or `this.value` if I add a little bit more logic in the initial set up.

Basically all that I need to do is in this [loop](https://github.com/hanford/angular-vdom/blob/master/index.js#L15) check if the value is there with `$scope.parent[key]`, and if the value doesn't exists, I need to do a check for `$scope.$parent[controllerAsVariable][key]` ... if the value still isn't present, perhaps I can somehow fail gracefully

Determining the controllerAsVariable should be pretty easy, as in that scenario all the `$scope.$parent` values are prefixed with a `$` and it might be a safe assumption that a controllerAs variable wouldn't be

Other then that, I'm not sure how to access that parent `$scope` safely. `.components()` are slightly different than directives as they _always_ have an isolated scope. You can see the differences between the two [here](https://docs.angularjs.org/guide/component)

**Comment by bendrucker** [comment]
Just write a unit tested PR and we can talk about it. Too many words not enough code. This library can receive the initial state but then you need to hook into Angular properly and return a real controller instance. If you take an initial state reference you need to create a controller that assigns that initial state on the instance. 

You're not supposed to do view manipulation in a `controller`. This is the core of any serious Angular development and you need to do each step in the right place.

**Comment by hanford** [comment]
@bendrucker ^ there is an example of what guessing controllerAs variables could look like.

Agreed that DOM manipulation doesn't belong in a controller, though `.components()` don't have a link function equivalent. And remember the goal here is simply for high performance rendering, so I think this solution is probably adequate for the time being.

I think I'll be okay if I explicitly suggest in the documentation the limitations here are that ControllerAs works as long as you're not using `$` in the name while `$scope`'d variables work fine. Unless I'm completely missing something, I'll probably start integrating support for for events

What might actually be a better solution is hardcoding the default $scope values that angular has, and that way I wouldn't need to "guess" what might be the controllerAs var

**Comment by bendrucker** [comment]
Why would you guess about this? You should be requiring the user to supply enough information about the location of their data to allow your library to unambiguously do what it needs to do.

**Comment by hanford** [comment]
Yep you're totally right and I was overthinking things.

Added support for a `controller-as="123"` attributue

**Comment by bendrucker** [comment]
Ok. I just read through the Angular component documentation. It is not the appropriate tool to use for a project like this. You need to use the directive API.
