### ISSUE TITLE
Receive DOM target from Angular instead of using `querySelector`

### ISSUE THREAD

**Issue by bendrucker** [hanford/angular-vdom#4]
Angular should pass the component an element to attach to instead of you getting one using a query

**Comment by hanford** [comment]
That makes things a lot trickier, the virtualComponent function can be called before angular has bootstraped, so if you're using a router, the element won't be on the DOM yet because of 
`<div ui-view></div>` hasn't been compiled yet

Any ideas?

**Comment by bendrucker** [comment]
That's the fun part!
