### ISSUE TITLE
Avoid updating the loop once per binding

### ISSUE THREAD

**Issue by bendrucker** [hanford/angular-vdom#5]
https://github.com/hanford/angular-vdom/blob/0113e4b6e85b93b6f49237f0fa2d0cce8b6d4dfd/index.js#L21-L29

If you have multiple bindings this won't work at all. Make sure you're iterating through all the bindings and getting the values from scope. I kinda doubt the `change` argument is required at all. Virtual DOM will do the diffing at the VNode level and you need to pass the loop the full component state on every change.

**Comment by hanford** [comment]
https://www.npmjs.com/package/map-values
