### ISSUE TITLE
rewrite

### ISSUE THREAD

**Issue by hanford** [hanford/angular-vdom#8]
So I'm rewriting this package w/ .directive() support instead of .component() and a few things are changing
- Add support for a virtual `state` composed of observables
- Allow the above `state` to trigger virtual-dom re-renders
- Allow the `state` to be preconfigured in angular land
- DOM manipulation will belong in the directives `link` function
- reduced complexity with data setting up the initial state of the directives data

[lib](https://github.com/hanford/angular-vdom/blob/167613e66276fe0e7a52275604440e12c57d80f6/index.js)

So instead of passing in a `render` function, you pass in the virtual component with the idea that the virtual component has a render function attached. Like this ->
`component.render = function render () { ....}`

Virtual components can be set up a few different ways, the way I use this is like this

``` js
// virtual component
var State = require('dover')
var h = require('virtual-dom/h')
var Observ = require('Observ')

module.exports = messageComponent

function messageComponent () {
  return State({
    message: Observ('')
  })
}

messageComponent.render = function render (state) {
 return h('div', state.message)
}
```

Then things over in angular are super straight forward

``` js
var ngVirtual = require('angular-vdom')
var messageComponent = require('./virtual-component')

module.exports = angular
  .module('example1', [])
  .directive('messageComponent', ngVirtual(messageComponent, {scope: {message: '<'}}))
  .name
```

And then the virtual component will render wherever the directive is used and will update when events happen in either angular, or the virtual component.

cc @bendrucker

**Comment by hanford** [comment]
@bendrucker

**Comment by bendrucker** [comment]
Need an example of how the message gets to the component

**Comment by hanford** [comment]
@bendrucker It's just an attr, so in the above case

``` html
<message-component message="message"></message-component>
```

The naming in the above example is pretty poor I now realize

Then in directive definition I generate, I [loop over all of the attrs](https://github.com/hanford/angular-vdom/blob/0b43045d4074e7d70c5468d417efaabca2645cba/index.js#L30) and set up watchers. When the watchers get a change, I `.set()` the observable which then re-renders

**Comment by bendrucker** [comment]
It's not a good example in general because there's no need to sync something like `message` between Angular and the observable when you can just pass it down. Encouraging users to load up components full of state is bad. Focus on making this work with `@eaze/product` since that's a properly written component. Once you can handle that it makes sense to tackle a broader goal.

**Comment by hanford** [comment]
@bendrucker integrating the product card is super easy. The only change that would need to made aside from deleting code is how you pass in `render(state, productData)` - Which is where I would need to make some changes to the lib as I currently only pass in the `state`.

My goal here is to lean off of angular, entirely where/when possible. This _doesn't_ need to be the greatest angular module of all time. It's to the point where I just want to write the bridge between Angular and vdom in which I can eventually entirely cross. I'm okay, with directives having several attrs, or this "bridge" only working _well_ with a predefined set of principles.

Disregard the above example, it's pseudo code to show how this works in the quickest way possible. I'm genuinely trying to move this forward and begin integrating this in different apps of mine. Us going back and fourth about these relatively minor detail feels like bike shedding, rather than constructive feedback.

**Comment by bendrucker** [comment]
Eaze-specific discussion shouldn't be in a public repo.
